### ISSUE TITLE
Is this the most up-to-date version?

### ISSUE THREAD

**Issue by ghostserverd** [drescherflo/Nintendont-MMMod-old#2]
If I wanted to compile this myself, is this the version I should use? It's named "old", but it seems to be more up to date than https://github.com/drescherflo/Nintendont-MMMod

Also I just want to say that the gamecube animation when launching Nintendont is amazing! Thanks for making this mod!

**Comment by drescherflo** [comment]
Yes, this is the most up-to-date version. I wanted to do a full rewrite of the mod as an official fork (with some bug fixes), but didn't have time to finish it yet.

**Comment by ghostserverd** [comment]
Perfect. Thanks for confirming!
